/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Banner from "../components/Banner";
import about from "../public/about.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import withAuth from "../auth/withAuth";

const aboutUs = () => {
  const { t, i18n } = useTranslation();
  return (
    <div>
      <Head>
        <title>About Us / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={about}
        imageUlt="about us banner"
        text1={t("about")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      {i18n.language === "ar" ? (
        <div className="h-full md:mb-44 mb-16 lg:max-w-4xl md:max-w-2xl max-w-sm mx-auto md:space-y-20 space-y-10">
          <div className="space-y-5 xl:mt-28 md:mt-20 mt-5 text-right">
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              تتولى مراكز تدبير مسؤولية تقديم خدمات استقدام وتشغيل عمال الخدمات
              المساعدة، وتخدم هذه المراكز المنتشرة في كافة أنحاء الدولة، الأسر
              المواطنة والمقيمة بإشراف من الوزارة وبما يحقق راحة المتعاملين
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                :وتشمل تلك الخدمات ما يلي{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  خدمات وزارة الموارد البشرية والتوطين المتعلقة بقطاع العمالة
                  المساعدة التي تقدم بالمركز
                </p>
                <p>
                  توفير عمالة مساعدة وفق متطلبات صاحب العمل وضمن الباقات
                  المتوفرة بالمركز
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                النجوم للعمالة المساعدة هي ثمرة تطوير قطاع العمالة المساعدة
                بالدولة. تأسس المركز بداية عام 2022 ضمن شراكه استراتيجيه واندماج
                تضم أربع مكاتب ذات خبره في المجال تمتد ما بين 20 الى 30 عام وهي
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>مكتب الشرق للخدمات</p>
                <p>مكتب سمارت للخدمات</p>
                <p>لولو للخدمات العامة</p>
                <p>العباد لجلب العمالة</p>
              </div>
            </div>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                فقد قررت المكاتب الأربعة الانضمام إلى هذه المهمة للتجمع للتغلب
                على التحديات العالمية الحالية على العمالة المنزلية وضمان تقديم
                خدمات ممتازة لمجتمعنا وعملائنا بما يتماشى مع قانون العمل
                الإماراتي وإرشادات وزارة الموارد البشرية والتوطين
              </h1>
              <div className="space-y-3">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  الرؤية: تقديم خدمات عمالة مساعدة شاملة بمستوى جودة غير مسبوق
                </h1>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  المهمة: توفير خدمات شامله ذات سياق آمن وسهل لمجال العمالة
                  المساعدة وأرباب العمل وتيسير تواصلهم لتحسين مجال الأعمال ضمن
                  نطاق يسوده الاحترام المتبادل ويعكس رضى عن مستوى الخدمات
                  المقدمة{" "}
                </h1>
                <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                  <p>الجودة في تقديم الخدمات </p>
                  <p>الابتداع </p>
                  <p>الاحترام</p>
                  <p>الكفاءة </p>
                  <p>التحسين والتطوير المستمر</p>
                </div>
              </div>
            </div>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                نتطلع إلى المشاركة في تقديم خدمة آمنة وممتازة لمجتمعنا وعملائنا
                والعمالة المنزلية. تنقسم خدماتنا الى فئتين أساسيتين وهما
              </h1>
              <div>
                <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                  <p>
                    خدمات العمالة المساعد والتي تندرج الى ثلاث باقات رئيسية
                    التقليدية، المرنة والمؤقتة
                  </p>
                  <p>خدمات تخليص المعاملات والطباعة</p>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                وبالتفصيل مراكز تدبير هي مراكز خدمة تم ترخيصها من قبل وزارة
                الموارد البشرية والتوطين في الإمارات، حيث جاءت نتيجة تعاون بين
                القطاع الحكومي والخاص بهدف تيسير استقدام العمالة إلى الدولة،
                ومساعدة الراغبين في استقدامهم ضمن ضوابط وشروط ومعايير وبإشراف
                مباشر من قبل الوزارة، وتشمل الخدمات ما يزيد عن 16 فئة من
                الوظائف، منها الحراسة الأمنية، والمربية المنزلية، والتدبير
                والنظافة المنزلية، والسائقين وغيرها الكثير من كلا الجنسين
              </h1>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                سيقدم المركز الخدمات التاليه{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>خددمات التوظيف</p>
                <p>
                  تلبية احتياجات العملاء للحصول على عاملة منزلية بدوام كامل/ أو
                  دوام جزئي
                </p>
                <p>تأمين الفيزا وتأشيرة الدخول</p>
                <p>إجراء فحص طبي شامل للعمال</p>
                <p>تأمين صحي للعاملات في المنزل</p>
                <p>توصيل العاملات من المطار إلى منزل العميل</p>
                <p>تدريب وتوجيه العاملات على أصول العمل</p>
                <p>إيجاد حلول للمشاكل بين العاملات وأرباب العمل</p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              مزايا مراكز الخدمة تدبير
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                تتنوع الأسباب التي تسوق أصحاب العمل لاختارمراكز الخدمة تدبير في
                تأمين عمالة منزلية وغيرها من فئات العمالة المساعدة، ومن هذه
                المزايا نذكر
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>يتم استقدام العمالة بطرق قانونية وسليمة.</p>
                <p>
                  مساعدة أصحاب العمل على الحصول على عمالة مساعدة بشكل قانوني دون
                  الوقوع في حالات غير قانونية تؤدي إلى مشاكل في الأوراق
                  والمستندات وخسائر مادية.
                </p>
                <p>الموازنة وحفظ حقول العمال وأصحاب العمل</p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              الفئات التي تستقدمها مراكز تدبير
            </h1>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                توفر مراكز تدبير مربية منزلية وتقوم بتدريبها قبل البدء بعملها
                توفر تدبير ما يزيد عن 16 فئة من العمالة التي يحتاجها سكان دولة
                الإمارات في حياتهم اليومية، وتشمل
              </h1>
              <div>
                <div className="text-[10px] md:flex md:flex-row-reverse md:space-x-10 md:text-base font-roboto font-semibold  ml-2 text-[#234F7E]">
                  <div className="md:space-y-2 md:ml-10">
                    <p>سائق</p>
                    <p>خادمة</p>
                    <p>معلم خاص</p>
                    <p>جليسة أطفال أو مربية</p>
                    <p>ممرضة خاصة</p>
                    <p>مدبرة منزل</p>
                    <p>وغيرها</p>
                  </div>
                  <div className="md:space-y-2">
                    <p>حارس </p>
                    <p>عاملة مساعدة</p>
                    <p>موارع</p>
                    <p>صياد</p>
                    <p>طاهية</p>
                    <p>رعاية كبار السن</p>
                  </div>
                </div>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              استراتيجية العمل في تدبير
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                تتبع مراكز تدبير استراتيجية معينة تتعلق باستقدام العمالة من
                مختلف بلدان العالم، وبعد الانتهاء من الوثائق والأعمال القانونية
                يتم تدريب العمال قبل مباشرة عملهم بطريقة رسمية، علاوةً على تنظيم
                ملفاتهم الشخصية؛ بهدف تسهيل الاختيار من قِبل أرباب العمل
                والأُسر، ثم تنظيم لقاء بين أصحاب العمل والعاملين, تعمل مراكز
                خدمة تدبير تعمل على تأمين عاملات منزلية للشركات الخاصة التي تعمل
                في هذا المجال، وتضمن توفير إقامة لهم.
              </h1>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              آلية توظيف عامل من مراكز تدبير{" "}
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                تعتبر عملية توظيف العمالة المنزلية من خلال مركز النجوم للعمالة
                المساعدة سهلة وسلسه وبعيدة عن التعقيد و التي تبدأ بالتواصل عبر
                الهاتف أو الطلب عبر الإنترنت، حيث سنقوم بتوفير ومشاركة العميل
                بكافة المعلومات وإيجاد أجوبة لكافة التساؤلات لتلبية طلب التوظيف،
                وتنقسم عملية توظيف عاملة منزلية إلى عدة خطوات
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E] space-y-3">
                <p>التواصل المباشر بمركز الخدمة لطلب العامل المنزلي</p>
                <p>
                  البحث عن طريق الموقع الالكتروني وطلب المقابلة للعامل المساعد
                </p>
                <p>
                  يقوم المركز بعدها بمشاركة ملفات العمال الشخصية التي تتطابق مع
                  البنود المذكورة أعلاه، ثم يتم تنظيم مقابلات مع الأشخاص الذين
                  وقع الاختيار عليهم مباشرة او تنسيق طلب المقابلات الإلكترونية
                </p>
                <p>
                  بمجرد انتهاء المقابلة بطريقة جيدة، يتم شرح الشروط التعاقدية
                  وفقاً لمتطلبات صاحب العمل وبنود التعاقد المنصوص عليها من قبل
                  وزارة الموارد البشرية والتوطين
                </p>
                <p>سيراعي العقد أيضاً الحقوق الأساسية للعمال ومتطلباتهم</p>
                <p>
                  تتابع مراكز تدبير مدى رضى العامل ورب العمل، وفي حال وجود خلاف
                  تعمل على إيجاد حل مناسب أو استبدال العامل بآخر، سواء كان الطلب
                  من قبل صاحب العمل أو العامل
                </p>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="h-full md:mb-44 mb-16 lg:max-w-4xl md:max-w-2xl max-w-sm mx-auto md:space-y-20 space-y-10">
          <div className="space-y-5 xl:mt-28 md:mt-20 mt-5">
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Tadbeer centers are responsible for providing recruitment and
              employment services for domestic workers. These centers which are
              spread throughout the country serves nationals, residents of
              United Arab Emirates and families under the supervision of
              Ministry of Human Resources and Emiratization to achieve the
              convenience of customers.
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                These services include:
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  - Services related to the domestic workers sector provided at
                  the Centre.
                </p>
                <p>
                  - Providing domestic workers according to the requirements of
                  the employer and within the packages available at the center.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                Al Nujoom Domestic workers is partnership organization among
                four UAE nationals. It’s a joint mission between four of the old
                Domestic Workers Offices which had between 20 and 30 plus years
                of experience at the field.
              </h1>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                Old offices where under business names of:
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>- Smart Service office</p>
                <p>- Lulu General Service</p>
                <p>- Al Abad Manpower Supply</p>
                <p>- East Service office</p>
              </div>
            </div>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                The offices decided to Join this mission to gather to overcome
                today{"'"}s global challenges on Domestic workers and to ensure
                provides excellent services to our community and customers in
                alignment to UAE labor law and Ministry of Human Recourses and
                Emiratization guidelines.
              </h1>
              <div>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  Our Values are:
                </h1>
                <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                  <p>- Quality</p>
                  <p>- Excellent Service Delivery</p>
                  <p>- Innovation</p>
                  <p>- Respect</p>
                  <p>- Efficiency</p>
                  <p>- Continuous Improvements</p>
                </div>
              </div>
            </div>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                We are looking forward to participating in providing safe and
                excellent service to our community, customers, and Domestic
                workers within our two service lines
              </h1>
              <div>
                <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                  <p>
                    1. Providing Domestic workers in three different packages
                    “Traditional, Flexible and temporarily”
                  </p>
                  <p>2. Transactional and typing Services.</p>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                In details, Tadbeer centers are service centers that have been
                licensed by the Ministry of Human Resources and Emiratization in
                the UAE, as they came as a result of cooperation between the
                government and private sectors with the aim of facilitating the
                recruitment of workers to the country and assisting those
                wishing to recruit them within the control, conditions and
                standards and under the direct supervision of the Ministry. The
                services include more than 16 categories of jobs, including
                security guards, housemaids, housekeeping, drivers, and many
                others from both sexes.
              </h1>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                The center will provide the following services:
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>1- Employment services</p>
                <p>
                  2- Meet client’s needs for a full-time/part-time domestic
                  worker
                </p>
                <p>3- Securing visa and entry visa</p>
                <p>
                  4- Conducting a comprehensive medical examination for workers
                </p>
                <p>5- Health insurance for domestic workers</p>
                <p>
                  6- Delivery of workers from the airport to the client’s house
                </p>
                <p>7- Training and guiding female workers on work assets</p>
                <p>
                  8- Finding solutions to problems between workers and sponsors
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              WHY TADBEER?
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                Tadbeer service centers are approved by Ministry of Human
                Resources and Emiratization “MOHRE” and they have a transparent
                system to hire Domestic workers in UAE
              </h1>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                There are several reasons why you should select Tadbeer centres
                to hire domestic workers in the UAE.{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>
                  1- They use legal channels approved by governments to hire
                  domestic workers.
                </p>
                <p>
                  2- Helping employers to obtain domestic worker legally without
                  falling into illegal cases that lead to problems with papers
                  and documents and financial losses.
                </p>
                <p>
                  3- Budgeting and preserving the fields of workers and
                  employers.
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Clasicifications of Domestic workers
            </h1>
            <div className="space-y-3">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                There are 19 categories of domestic household staff that can be
                employed which includes,
              </h1>
              <div>
                <div className="text-[10px] md:flex md:space-x-10 md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                  <div className="md:space-y-2">
                    <p>• Housekeeper,</p>
                    <p>• Housemaid,</p>
                    <p>• Private nurse,</p>
                    <p>• Private pro,</p>
                    <p>• Gardener,</p>
                    <p>• Private agriculture engineer,</p>
                    <p>• Cook,</p>
                    <p>• Parking valet worker,</p>
                  </div>
                  <div className="md:space-y-2">
                    <p>• Private coach,</p>
                    <p>• Household shepherd,</p>
                    <p>• Household caretaker,</p>
                    <p>• Family chauffeur,</p>
                    <p>• Babysitter,</p>
                    <p>• Security guard,</p>
                    <p>• Private teacher,</p>
                    <p>• Household horse groomer.</p>
                    <p>• Private sailor,</p>
                  </div>
                </div>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Tadbeer Business Management strategy
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                Al Nujoom Domestic Workers follow a specific strategy related to
                the recruitment of workers from different countries around the
                world. After the completion of documents gathering and approvals
                to legally works, Al Nujoom will post the CV’s to be available
                for clints. At the same time, our agencies in other countries or
                our staff at the center will train the workers on technical and
                cultural awareness. In addition to organizing their personal
                files and maintain having UpToDate information, We aim to
                facilitate the selection process and support the employers to
                best possible selection, we coordinate and organize an interview
                meeting between employers and employees.
              </h1>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Mechanism of recruiting a worker from Al Nujoom center{" "}
            </h1>
            <div className="space-y-2">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                Clints can easily contact us over the phone, visit our Centre or
                initiate a request for domestic worker by visiting our website
                www.TadbeerAlnujoom.com The process of hiring a domestic worker
                is divided into the following.
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E] space-y-3">
                <p>
                  • Direct contact of our staff at Al Nujoom Domestic workers to
                  place a request.
                </p>
                <p>
                  • Search thought our website www.TadbeerAlNujoom.com to view
                  available maids and book an interview.
                </p>
                <p>
                  • The center then shares the worker’s personal information
                  that match the above items, then organizes interviews with the
                  selected persons directly or coordinates the distance
                  interview request.
                </p>
                <p>
                  • Once the interview is well over, the contractual terms are
                  explained in accordance with the employer’s requirements and
                  the terms defined by Ministry of Human Resources and
                  Emiratization “Mohre”.
                </p>
                <p>
                  • The contract will also take into account the basic rights
                  and requirements of workers.
                </p>
                <p>
                  • Al Nujoom Domestic workers will follow up on the
                  satisfaction of the worker as well as the employer. In case of
                  an event of a disagreement, Al Nujoom work to find an
                  appropriate solution or replace the worker with another,
                  whether the request is by the employer or the worker.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      <Footer />
    </div>
  );
};

export default withAuth(aboutUs);
