/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState } from "react";
import Banner from "../components/Banner";
import contact from "../public/contact.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import Map, { Marker } from "react-map-gl";
import withAuth from "../auth/withAuth";

const contactUs = () => {
  const { t, i18n } = useTranslation();
  return (
    <div>
      <Head>
        <title>Contact Us / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={contact}
        imageUlt="Contact us banner"
        text1={t("contact")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="grid grid-cols-2 bg-[#E7EDF3] md:mb-32 mb-10">
        <div>
          <Map
            mapStyle="mapbox://styles/mapbox/streets-v12"
            mapboxAccessToken="pk.eyJ1Ijoia2FyaW1raGFsZWRlbG1hd2UiLCJhIjoiY2wxa3l4bDRjMDN6ZDNjb2JnbWpzbGVncSJ9.Hr7IeGn4060vCiHaeJH1Zw"
            initialViewState={{
              longitude: 55.51717438199587,
              latitude: 25.256243436006198,
              zoom: 12,
            }}
          >
            <Marker
              longitude={55.51717438199587}
              latitude={25.256243436006198}
              anchor="right"
              color="#FF0000"
              style={{
                cursor: "pointer",
              }}
            ></Marker>
          </Map>
        </div>
        <div
          className={`md:my-10 xs:my-2 lg:space-y-10 md:space-y-7 xl:max-w-xl w-full mx-auto ${
            i18n.language === "ar" ? "text-right" : "text-left"
          }`}
        >
          <h1 className="text-[#E48100] font-lato font-extrabold md:text-2xl text-lg">
            {t("connect")}
          </h1>
          <div
            className={`flex ${
              i18n.language === "ar"
                ? "xs:flex-row-reverse flex-col"
                : "xs:flex-row flex-col"
            } lg:space-x-16 md:space-x-10 xs:sapce-x-4 space-y-2 xs:space-y-0 xs:space-x-4 space-x-0`}
          >
            <div className={i18n.language === "ar" ? "md:ml-20 ml-5" : ""}>
              <h2 className="lg:text-xl md:text-base text-[10px] font-roboto text-[#234F7E]">
                {t("location")}
              </h2>
              <p className="lg:text-base text-xs text-[6px] ">
                Agriculture Building,
              </p>
              <p className="lg:text-base text-xs text-[6px] ">
                {" "}
                Stores land, Maliha Road,
              </p>
              <p className="lg:text-base text-xs text-[6px] ">Sharjah, UAE.</p>
            </div>
            <div className="space-y-4">
              <div>
                <h2 className="lg:text-xl md:text-base text-[10px] font-roboto text-[#234F7E]">
                  {t("callCenter")}
                </h2>
                <p className="lg:text-base text-xs text-[7px] ">
                  06-767-4222 / 054-992-9926
                </p>
              </div>
              <div>
                <h2 className="lg:text-xl md:text-base text-[10px] font-roboto text-[#234F7E]">
                  {t("email")}
                </h2>
                <a
                  href="mailto:Alnujoomshj@gmail.com"
                  className="lg:text-base text-xs text-[7px] underline"
                >
                  Alnujoomshj@gmail.com
                </a>
              </div>
            </div>
          </div>
          <div className="bg-[#E7EDF3] py-5 md:px-4 xs:px-2">
            <form action="" method="post" className="md:space-y-5 space-y-2">
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="text"
                  className={`block py-2.5 ${
                    i18n.language === "ar" ? "text-right" : "text-left"
                  } px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  placeholder=" "
                  required
                />
                <label
                  className={`peer-focus:font-medium ${
                    i18n.language === "ar" ? "right-2" : "left-0"
                  } absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6`}
                >
                  {i18n.language === "ar" ? "الاسم" : "Name"}
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="email"
                  className={`block py-2.5 ${
                    i18n.language === "ar" ? "text-right" : "text-left"
                  } px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  placeholder=" "
                  required
                />
                <label
                  className={`peer-focus:font-medium ${
                    i18n.language === "ar" ? "right-2" : "left-0"
                  } absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6`}
                >
                  {i18n.language === "ar"
                    ? "البريد الالكتروني"
                    : "Email address"}
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="tel"
                  className={`block py-2.5 ${
                    i18n.language === "ar" ? "text-right" : "text-left"
                  } px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  placeholder=" "
                  required
                />
                <label
                  className={`peer-focus:font-medium ${
                    i18n.language === "ar" ? "right-2" : "left-0"
                  } absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6`}
                >
                  {i18n.language === "ar" ? "رقم الهاتف" : " Phone number"}
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <textarea
                  className={`block py-6 px-0 w-full  ${
                    i18n.language === "ar" ? "text-right" : "text-left"
                  } xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  placeholder=""
                  rows={5}
                  required
                />
                <label
                  className={`peer-focus:font-medium  ${
                    i18n.language === "ar" ? "right-2" : "left-0"
                  } absolute text-sm text-[#234F7E] duration-300 transform -translate-y-1 scale-75 top-3 -z-10 origin-[0] peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6`}
                >
                  {i18n.language === "ar" ? "الرسالة" : " Message"}
                </label>
              </div>
              <button
                type="submit"
                className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto sm:px-5 sm:py-2.5 px-3 py-1.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
              >
                {i18n.language === "ar" ? "ارسل رسالتك" : " Send a message"}
              </button>
            </form>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(contactUs);
