/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Banner from "../components/Banner";
import about from "../public/about.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import withAuth from "../auth/withAuth";
import { useRouter } from "next/router";
const faq = () => {
  const { t, i18n } = useTranslation();
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Faqs / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={about}
        imageUlt="faqs us banner"
        text1={t("faqs")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      {i18n.language === "ar" ? (
        <div className="h-full md:mb-44 mb-16 lg:max-w-4xl md:max-w-2xl max-w-sm mx-auto md:space-y-20 space-y-10">
          <div className="space-y-5 xl:mt-28 md:mt-20 mt-5 text-right">
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              أسئلة متعلقة بالأعمال
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                هل النجوم مركز خدمه تدبير؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  نعم. نحن مركز مرخص للمركز الخدمه تدبير في دولة الإمارات
                  العربية المتحدة. حصلنا على ترخيصنا في يناير من عام 2022.
                  ولدينا معدل متميز وفقًا لقياسات وزارة الموارد البشرية والتوطين
                  بدولة الإمارات العربية المتحدة (MOHRE)
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هو تدبير؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  مراكز تدبير مسؤولة عن توفير خدمات التوظيف والمتابعة للعمال
                  المنزليين. هذه المراكز المنتشرة في جميع أنحاء الدولة تخدم
                  المواطنين والمقيمين في دولة الإمارات العربية المتحدة والعائلات
                  تحت إشراف وزارة الموارد البشرية والتوطين لتحقيق الراحة
                  للعملاء. تشمل هذه الخدمات
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  الخدمات المتعلقة بقطاع العمالة المنزلية التي يقدمها المركز
                </p>
                <p>
                  توفير العمالة المنزلية حسب متطلبات صاحب العمل وضمن الحزم
                  المتوفرة في المركز
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                أين موقع النجوم للعمالة المنزلية؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  يقع مركز النجوم للعمالة المنزلية في مدينة الشارقة في مبنى
                  دائرة الزراعة ، أرض المستودعات، طريق مليحة
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي المناطق التي يخدمها مركز النجوم؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  يتوزع عملاء مركز النجوم للعمالة المساعدة في إمارة الشارقة وحول
                  الإمارات العربية المتحدة. نحن نخدم العملاء في جميع أنحاء
                  الإمارات العربية المتحدة حيث لدينا أيضًا خط خدمات عن بعد.
                  يمكننا إنهاء كافة الإجراءات وتسليم العاملة المنزلية إلى جهة
                  العمل. يمكن أن تكون جميع معاملات الطباعة خدمات من الباب إلى
                  الباب أيضًا
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              عملية التوظيف{" "}
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                لماذا نتعامل مع مركز النجوم للعمالةو المساعدة؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  مركز النجوم للعمالة المنزلية ذ.م.م هو مركز معتمد ومرخص من قبل
                  وزارة الموارد البشرية والتوطين بدولة الإمارات العربية المتحدة
                  (MOHRE). نقدم ضمانًا لمدة عامين على الحزمة التقليدية حيث يمكن
                  للعملاء الحصول على المبلغ المعلق في غضون أسبوعين. يمكن
                  لموظفينا المتفانين تقديم خدمة ذات طابع شخصي للعملاء وتوجيه
                  العملاء على أختيار أفضل العاملات من خلال فهم متطلبات العميل.
                  تتوافق أسعارنا مع رسوم وزارة الموارد البشرية والتوطين. تضيف
                  خبرتنا الطويلة في السوق الكثير لرحلة عملائنا
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي مميزات الاستعانة بعمالة منزلية من شركة النجوم للعمالة
                المنزلية؟
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  الوصول في الوقت المحدد
                </h1>
                <p>
                  عرض السيرة الذاتية لعامل الخدمة المنزلية بالإضافة إلى مقاطع
                  الفيديو ، ومقابلة وتوظيف المفضلة لديك. سنقوم بتوصيلها إليك في
                  نفس اليوم إذا كانت داخل البلد. للمتقدمين من خارج الدولة ، لدى
                  النجوم اتفاقيات مع وكالات خارجية لتسريع عملية جلب العامل إلى
                  الإمارات العربية المتحدة
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  خيارات الدفع
                </h1>
                <p>
                  فقط قم بتحميل التفاصيل المصرفية الخاصة بك. ادفع عبر الإنترنت
                  في 5 دقائق. لدينا أيضًا خيار تحويل المبلغ إلى حساب النجوم
                  المصرفي أو تسليم المبلغ النقدي إلى مندوبنا
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  ضمان لمدة عامين
                </h1>
                <p>
                  إذا حدث خطأ ما (مثل الخادمة الهاربة أو الحمل) ، فنحن مسؤولون
                  عن التعامل مع أي دعاوى قضائية أو زيارات لمراكز الشرطة ، وليس
                  أنت. بالإضافة إلى ذلك ، سنقوم باستبدال عاملة منزلية بأخرى
                  جديدة أو إعادة أموالك في غضون أسبوعين كحد أقصى. نتبع كافة
                  قوانين وزارة الموارد البشرية والتوطين في ذلك
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  الاستبدال
                </h1>
                <p>
                  إذا لم تعجبك العاملة المنزلية التي اخترتها للحزمة التقليدية ،
                  فيمكنك فقط اختيار واستبدالها بعاملةأخرى أثناء التجربة. يمكن
                  استبدال الحزم المرنة والمؤقتة في أي وقت
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  يمكنك الإلغاء في أي وقت
                </h1>
                <p>
                  يمكن الإلغاء المرن والمؤقت في أي وقت ولأي سبب كان. سنعيد
                  خادمتك أوبر إلى مكان إقامتنا ونوقف جميع مدفوعاتك المستقبلية.
                  لا توجد فترة إشعار مطلوب. لا توجد رسوم إلغاء. يتم تطبيق
                  إرشادات وزارة الموارد البشرية والتوطين (MOHRE) على الحزم
                  التقليدية أيضًا. يحسب الإحراج لتحديد المبلغ المعلق. مثال "إذا
                  كان العقد 15000 لمدة 24 شهرًا ، فيجب إعادة مبلغ 7500 إذا تم
                  إرجاع الخادمة في الشهر 12
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  رعاية الأطفال أو الطبخ أو التنظيف أو غيرها من المهارات
                  المطلوبة.
                </h1>
                <p>
                  تتمتع معظم الخادمات لدينا بخبرة جيدة للغاية بمهارات مختلفة.
                  بناءً على احتياجاتك ، سيدعم ممثل النجوم أفضل الخيارات. لمعرفة
                  المزيد عن تجربة خادمة معينة ، يرجى الاطلاع على السيرة الذاتية
                  والفيديو
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                كيف يمكنني اختيار أفضل عامل منزلي مناسب؟
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  حدد احتياجاتك ومجموعة المهارات المطلوبة ، واختر جنسيتك المفضلة
                  وميزانيتك المالية ، ثم:-
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              لتوظيف عاملة بدوام كامل{" "}
            </h1>
            <div className="space-y-1">
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>ابحث واختر من بين مئات الخادمات المتوفرين</p>
                <p>حدد أفضل تطابق لديك واطلب إجراء المقابلات</p>
                <p>
                  اتصل أو ما "يصل رقم الهاتف المحمول المباشر للحصول على التفاصيل
                  أو الدعم
                </p>
                <p>تأكيد الاختيار</p>
                <p>قم بالدفع المسبق وحدد ما إذا كنت بحاجة إلى التوقف والوقت </p>
                <p>توقيع العقود التي قدمها مندوبنا أثناء إسقاط العامل</p>
                <p>جرب الخادمة لمدة أربعة أيام ثم أكمل المدفوعات</p>
                <p>أكد لنا للحصول على تأشيرة عملية</p>
                <p>
                  الرجاء الضغط{" "}
                  <button
                    className="underline decoration-blue-500 text-blue-700 font-bold"
                    onClick={() =>
                      router.push({
                        pathname: "/findMaids",
                      })
                    }
                  >
                    هنا
                  </button>{" "}
                  لبدء مشاهدة الخادمات
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي المستندات المطلوبة للتوظيف؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  لتوقيع عقد مع عامل الخدمة المنزلية في النجوم ، سنطلب نسخة من
                  بطاقة الهوية الإماراتية الخاصة بك وكذلك نسخة من جواز السفر
                </p>
                <p>
                  قد تتطلب الخدمات المتعلقة بطباعة المعاملات مستندًا مختلفًا حسب
                  الخدمة المطلوبة
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              الخدمات{" "}
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي الخدمات المختلفة التي تقدمها تدبير؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  تقدم تدبير خدمات ضمن خطي الخدمة الرئيسيين لدينا{" "}
                </h1>
                <p>
                  الباقة التقليدية: تكلفه تتراوح من 5000 درهم إلى 15000 درهم حسب
                  جنسية العاملة المنزلية. سيتعين عليك أيضًا دفع رسوم تأشيرة
                  العاملة الخاصة بك بمجرد انضمامها إليك.
                </p>
                <p>
                  الباقة المؤقتة: اتفاقية لمدة 24 شهرًا. ستقوم بتحرير 24 شيكًا
                  مؤجلًا بدءًا من 2300 درهم إماراتي / الشهر. الخادمة تبقى على
                  تأشيرتنا.
                </p>
                <p>
                  الباقة المرنة: يمكنك مشاهدة فيديوهات الخادمات على موقعنا
                  وتوظيف المفضلة لديك. يمكنك الإلغاء في أي وقت. تتوفر الخطط
                  الأسبوعية والشهرية والسنوية ابتداءً من 2700 درهم / شهريًا.
                  الخادمة تبقى على تأشيرتنا.
                </p>
                <p>خدمات المعاملات والطباعة.</p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي الباقات التي تقدمها مركز الخدمة تدبير؟
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  لباقات الرئيسية الثلاث المتعلقة بالعمال المنزليين هي
                </h1>
                <p>
                  أ- الباقة التقليدية: خدمات الاستقدام لعامل الخدمة المنزلية من
                  داخل أو خارج الدولة التي يكفل فيها صاحب العمل العامل المنزلي
                  ويبقى معه خلال مدة العقد
                </p>
                <p>
                  ب- الباقة المؤقتة: هي خدمة توفير عاملة منزلية مكفولة من قبل
                  مركز خدمة تدبير للعمل لمدة تعاقدية. وبعد ذلك يُسمح للعامل أو
                  لا يُسمح له بالتحويل كعامل منزلي مقيم على كفالة صاحب العمل إذا
                  اتفقت الأطراف المعنية
                </p>
                <p>
                  ج- الباقة المرنة: العمالة المنزلية المكفولة من قبل مركز خدمة
                  تدبير للعمل بنظام مرن (ساعات ، أيام ، أسبوع)
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي خدمات الطباعة التي تقدمها النجوم؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  جميع خدمات الطباعة الحكومية المتعلقة بالتوظيف وتأشيرات الدخول
                  للعمال المنزليين والمنزليين ، بما في ذلك على سبيل المثال لا
                  الحصر ما يلي
                </h1>
                <p>أ- تصريح الدخول</p>
                <p>ب- تغيير الوضع</p>
                <p>ج- الهوية الإماراتية / الهوية الوطنية</p>
                <p>د- التأمين الحكومي والصحي</p>
                <p>هـ- الفحص الطبي</p>
                <p>و- طلب ختم تأشيرة الإقامة</p>
                <p>ز- تجديد تأشيرة العمالة المنزلية</p>
                <p>ح- إلغاء تأشيرة العمالة المنزلية</p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              الأسعار{" "}
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                كم هو راتب العاملة المنزلية؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  تم التحقق من رواتب الخادمات على أساس الجنسية والخبرة للحزمة
                  التقليدية. تتراوح الرواتب بين 1000 درهم و 1500 درهم إماراتي.
                  يُسمح بتطبيق المزايا وفقًا لقيم العمالة الإماراتية المنخفضة
                </h1>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي التكلفة الإجمالية للعمالة المنزلية؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  التحقق من التكلفة الإجمالية للعمال المنزليينبين
                </h1>
                <p>
                  عمولة المكتب التي تتراوح بين 5000 AE و 15000 AE باستثناء ضريبة
                  القيمة المضافة على أساس الجنسية
                </p>
                <p>
                  طباعة رسوم المعاملات مثل تصريح العمل ، تغيير الحالة ، هوية
                  الإمارات ، الفحوصات الطبية والتأشيرات
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي سياسة الإسترداد؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  خلال الفترة التجريبية ، إذا تم إرجاع العامل المنزلي ، فسيتم
                  إعادة المبلغ المقدم على الفور
                </h1>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  خلال الشهر الأول من الععمل يتم إرجاع المبلغ بالكامل مع مبالة
                  التكاليف للاقامة خلال أسبوعين ضمن اشتراطات وزارة الموارد
                  البشرية والتوطيبن
                </h1>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  بعد فترة الاختبار ، سيتم تقسيم المبلغ الإجمالي المدفوع على 24
                  شهرًا ، ويتم إرجاع المبلغ المعلق لفترة العقد المعلقة بناءً على
                  تعليمات وزارة اللجوء البشري والتوطين "Mohre" في غضون أسبوعين
                </h1>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              سياسة الإلغاء
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                ما هي سياسة إنهاء العقد؟
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  بعد فترة الاختبار ، سيتم تقسيم المبلغ الإجمالي المدفوع على 24
                  شهرًا ، ويتم إرجاع المبلغ المعلق لفترة العقد المعلقة بناءً على
                  تعليمات وزارة اللجوء البشري والتوطين "مهر" في غضون أسبوعين
                </h1>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                متى سيتلقى العميل المبلغ المسترد؟{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  سيكون السداد فوريًا أثناء فترة التجربة. بعد فترو التجربة ،
                  سيكون المبلغ المسترد في غضون 14 يومًا
                </h1>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="h-full md:mb-44 mb-16 lg:max-w-4xl md:max-w-2xl max-w-sm mx-auto md:space-y-20 space-y-10">
          <div className="space-y-5 xl:mt-28 md:mt-20 mt-5">
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Business related Questions:
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                Are you Tadbeer?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Yes. We are Tad-Beer licensed center in the UAE. We received
                  our licensed in January of 2022. and we have the highest
                  Tad-beer rank as measured by the UAE ministry of Human
                  Resources & Emiratization (MOHRE).
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What is Tadbeer?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Tadbeer centers are responsible for providing recruitment and
                  employment services for domestic workers. These centers which
                  are spread throughout the country serves nationals, residents
                  of United Arab Emirates and families under the supervision of
                  Ministry of Human Resources and Emiratization to achieve the
                  convenience of customers. These services include:
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  - Services related to the domestic workers sector provided at
                  the Centre.
                </p>
                <p>
                  - Providing domestic workers according to the requirements of
                  the employer and within the packages available at the center.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                Where Is Al Nujoom Domestic Workers location?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Al Nujoom Domestic Workers Center is located at Sharjah City
                  at Department of Agriculture Building, Stores land, Maliha
                  Road.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                Which areas does Al Nujoom Serve?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Al Nujoom service customers at Sharjah Emirate and around
                  United Arab Emirates. We serve customers all over the UAE
                  where we also have distance services line. We can finish all
                  the process and deliver the Domestic Worker to the employer
                  house. All typing transaction can be door to door services
                  too.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-bold">
                Al Nujoom Domestic workers is partnership organization among
                four UAE nationals. It’s a joint mission between four of the old
                Domestic Workers Offices which had between 20 and 30 plus years
                of experience at the field.
              </h1>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                Old offices where under business names of:
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>- Smart Service office</p>
                <p>- Lulu General Service</p>
                <p>- Al Abad Manpower Supply</p>
                <p>- East Service office</p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Hiring Process:
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                Why Should you hire from Al Nujoom Domestic workers?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Al Nujoom Domestic Workers LLC is certified and licensed
                  center by the UAE ministry of Human Resources & Emiratization
                  (MOHRE). We provide two years guarantee on the Traditional
                  Package where customers can get his pending amount within two
                  weeks. Our dedicated Secretaries can provide personalized
                  service to customer as they are from the same nationality of
                  the Domestic workers to support best choice worker. Our prices
                  are aligned with the Ministry of Human Resources &
                  Emiratization (MOHRE) Charges. Our long Experience at the
                  market adds a lot to our customer’s journey.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What are the advantages of hiring Domestic workers from Al
                Nujoom Domestic Workers?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  On Time Arrivals
                </h1>
                <p>
                  View the domestic worker Resume as well as videos, Interview
                  and hire your favorite. We will drop her to you on the same
                  day if she is inside the country. For outside the country
                  applicants, Al Nujoom has agreements with outside Agencies to
                  faster the process bringing the worker to the UAE.
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  Payments Options
                </h1>
                <p>
                  Just upload your bank details. Pay online in 5 minutes. We
                  also have option to transfer the amount to Al Nujoom bank
                  account account or to hand the amount cash to our
                  representative.
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  Two years Guaranteed{" "}
                </h1>
                <p>
                  If anything goes wrong (e.g. runaway maid, pregnancy), we’re
                  responsible to deal with any lawsuits or visits to police
                  stations, not you. In Addition, we will be replacing the
                  Domestic worker with an new one or return your Money within
                  maximum two weeks.
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  Replacements{" "}
                </h1>
                <p>
                  If you don’t like the maid you selected for traditional
                  package, you may just select and replace with another one
                  during trial. Flexible and Temporary packages can be replaced
                  at any times.
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  Cancel anytime
                </h1>
                <p>
                  Flexible and Temporary can be cancel anytime for whatever
                  reason. We’ll Uber your maid back to our accommodation and
                  stop all your future payments. No notice period is required.
                  No cancellation fees. Ministry of Human Resources &
                  Emiratization (MOHRE) guideline are applied for the
                  Traditional packages too. Embarrassment shall be calculated to
                  define the pending amount. Example “if the contract is 15000
                  for 24 months, an amount of 7500 shall be returned if the maid
                  was returned on month 12.
                </p>
              </div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
                  Childcare, Cooking, Cleaning, or other required skills.
                </h1>
                <p>
                  Most of our maids have very good experience with different
                  skills. Based on your needs, Al Nujoom representative will
                  support best choices. To know more about a specific maid's
                  experience, please view the domestic worker CV and video.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                How can I select the best fit Domestic Worker?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  Identify your needs and set of required Skills, Select your
                  preferred nationality and financial budget, then,
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              To hire a full-time maids simply:
            </h1>
            <div className="space-y-1">
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>• Search and select from hundreds of available maids</p>
                <p>• Select your best match and request for interviews.</p>
                <p>
                  • Call or What ‘up the direct mobile number for details or
                  support.{" "}
                </p>
                <p>• Confirm the choice. </p>
                <p>
                  • Make advance payment and select if you need drop and time.{" "}
                </p>
                <p>
                  • Sign the contracts given by our representative while
                  dropping the worker.
                </p>
                <p>• Try the Maid for four days then complete the payments. </p>
                <p>• Confirm to us for process visa. </p>
                <p>
                  • Please click{" "}
                  <button
                    className="underline decoration-blue-500 text-blue-700 font-bold"
                    onClick={() =>
                      router.push({
                        pathname: "/findMaids",
                      })
                    }
                  >
                    here
                  </button>{" "}
                  to start viewing maids
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What are the documents required for the hiring?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <p>
                  To sign a contract with Al Nujoom Domestic worker, We will ask
                  for your Emirates ID copy as well as passport copy.
                </p>
                <p>
                  Services related to Typing transaction may require different
                  document as per of the required service.
                </p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Services:
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What are the different Services provided by Tadbeer?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  Tadbeer provides services within our two major service lines
                </h1>
                <p>
                  1- Traditional Package: Upfront, non-refundable payment
                  ranging from AED 5,000-AED 15,000 depending on the maid's
                  nationality. You'll also have to pay for your maid's visa as
                  soon as she joins you.
                </p>
                <p>
                  2- Temporary Package: 24-month agreement. You’ll write 24
                  post-dated cheques starting from AED 2,300/month. Maid stays
                  on our visa.
                </p>
                <p>
                  3- Flexible Package: You can view maids' videos on our website
                  and hire your favorite. Cancel anytime. Weekly, monthly, and
                  yearly plans available, starting from AED 2,700/month. Maid
                  stays on our visa.
                </p>
                <p>4- Transactional and typing Services.</p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What are the Packages provided by Tadbeer?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  The three major Packages related to Domestic workers are: -
                </h1>
                <p>
                  A- Traditional Package: Recruitment services for a domestic
                  worker from in or outside the country where the domestic
                  worker is sponsored by the employer and stays with them during
                  the contract period.
                </p>
                <p>
                  B- Temporary Package: This service is providing a domestic
                  worker sponsored by Tadbeer service center to work for a
                  contractual period. After which the worker is or is not
                  allowed to transfer as a resident domestic worker sponsored by
                  the employer if the concerned parties agree.
                </p>
                <p>
                  C- Flexible Package: Domestic worker sponsored by Tadbeer
                  service center to work on a flexible system (hours, days,
                  week)
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What are the typing services Al Nujoom Provides?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  All government typing services pertaining to the employment
                  and entry visas of domestic and household workers, including
                  but limited to the following:
                </h1>
                <p>A- Entry Permit.</p>
                <p>B- Change of Status.</p>
                <p>C- Emirates Identity/ National ID.</p>
                <p>D- Government and Medical Insurance. </p>
                <p>E- Medical Test</p>
                <p>F- Residency Visa Stamping Application.</p>
                <p>G- Domestic Worker Visa Renewal.</p>
                <p>H- Domestic Worker Visa Cancellation.</p>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Pricing:{" "}
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                How much is Maid Salary?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  Maids Salaries are verifies based on Nationality and
                  Experience for Traditional Package. Salaries are between AED
                  1000 and AED 1500. Benefits are allowed applied as per of
                  United Arab Emirates Labor low.
                </h1>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What is the total cost for Domestic worker?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  Total Cost for Domestic Workers verify between
                </h1>
                <p>
                  • Office Commission which is between AE 5000 and AE 15000
                  excluding Vat based on Nationality.
                </p>
                <p>
                  • Typing transaction fees such as work permit, Status Change,
                  Emirates ID, Medical Tests and Visa.
                </p>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What is the reimbursement policy?{" "}
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  During Trial period If Domestic worker is returned, then the
                  Advance amount will be returned immediately,{" "}
                </h1>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  During the 1st month, Full amount shall be returned with in
                  two weeks.
                </h1>
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  After Probation period, the total amount paid will be divided
                  on the 24 months, pending amount of pending contract period
                  shall be returned based on the Mistry of Human Recourse and
                  Emiratization “Mohre” instructions within two weeks.
                </h1>
              </div>
            </div>
            <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
              Cancellation Policy:
            </h1>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                What is the contract termination policy?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  After Probation period, the total amount paid will be divided
                  on the 24 months, pending amount of pending contract period
                  shall be returned based on the Mistry of Human Recourse and
                  Emiratization “Mohre” instructions within two weeks.
                </h1>
              </div>
            </div>
            <div className="space-y-1">
              <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
                When will Customer received the reimbursed amount?
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
                <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                  Reimbursement will be immediate during Trail. After Trial
                  reimbursed amount will be within 14 days.
                </h1>
              </div>
            </div>
          </div>
        </div>
      )}

      <Footer />
    </div>
  );
};

export default withAuth(faq);
