import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matrixtudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      {/* Hero */}
      <section id="home">
        <Hero />
      </section>
      {/* About Us */}
      <section id="about">
        <About />
      </section>
      {/* Elituer - Our Product Brand */}

      {/* FKF - Our NGO Partner */}

      {/* Footer */}
    </div>
  );
}
