import Head from "next/head";
import About from "../components/About";
import Elit from "../components/Elit";
import Fkf from "../components/Fkf";
import Footer from "../components/Footer";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="h-screen overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-track-white/50 scrollbar-thumb-[#624de3]">
      <Head>
        <title>Matrixtudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      {/* Hero */}
      <section id="home">
        <Hero />
      </section>
      {/* About Us */}
      <section id="about">
        <About />
      </section>
      {/* Elituer - Our Product Brand */}
      <section id="elit">
        <Elit />
      </section>
      {/* FKF - Our NGO Partner */}
      <section id="fkf">
        <Fkf />
      </section>
    </div>
  );
}
