/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Banner from "../components/Banner";
import ourTeams from "../public/ourTeam.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import Team from "../components/Team";
import withAuth from "../auth/withAuth";

const ourTeam = () => {
  const { t, i18n } = useTranslation();

  return (
    <div>
      <Head>
        <title>Our Team / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={ourTeams}
        imageUlt="out team banner"
        text1={t("team")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <Team />
      <Footer />
    </div>
  );
};

export default withAuth(ourTeam);
