/* eslint-disable react-hooks/rules-of-hooks */
import { ArchiveBoxIcon, CheckCircleIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import paymentSuccess from "../public/paymentSuccess.png";
import withAuth from "../auth/withAuth";
const success = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Payment success / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Header />
      <div className="grid lg:grid-cols-2 grid-cols-1 xl:py-36 lg:py-20 py-6">
        <div className="space-y-6 xl:max-w-2xl lg:max-w-sm md:max-w-full xxs:max-w-xs max-w-[300px] mx-auto md:mt-28 mt-5">
          <div className="space-y-3">
            <h1 className="md:text-5xl xxs:text-xl text-lg font-lato font-bold text-gray-800">
              Payment successful
            </h1>
            <p className="md:text-lg text-xs font-roboto font-semibold text-gray-600">
              Thank you for choosing{" "}
              <span className="underline decoration-yellow-500 text-black">
                Tadbeer Alnujoom
              </span>
              {", "}
              we will reach you soon
            </p>
          </div>
          <div className="flex w-full">
            <div className="flex items-center">
              <CheckCircleIcon className="h-6 w-6 text-green-700" />
              <div className="h-[5px] xl:w-52 lg:w-32 md:w-48 w-28 bg-green-700" />
            </div>
            <div className="flex items-center">
              <CheckCircleIcon className="h-6 w-6 text-green-700" />
              <div className="h-[5px] xl:w-52 lg:w-32 md:w-48 w-28 bg-gray-500" />
              <ArchiveBoxIcon className="h-6 w-6 text-gray-500" />
            </div>
          </div>
          <div className="flex justify-between w-full">
            <h4 className="font-lato font-bold xl:text-base xxs:text-xs text-[10px]">
              Maid Selected
            </h4>
            <h4 className="font-lato font-bold xl:text-base xxs:text-xs text-[10px]">
              Payment received
            </h4>
            <h4 className="font-lato font-bold xl:text-base xxs:text-xs text-[10px]">
              Processing report
            </h4>
          </div>
          <div className="flex items-center justify-end xl:pt-20 lg:pt-10">
            <button
              onClick={() =>
                router.push({
                  pathname: "/",
                })
              }
              className="xl:px-6 xl:py-2 lg:px-4 md:px-3 px-2 py-1 font-lato border border-[#242424] rounded-full uppercase xl:text-base lg:text-sm text-[10px] tracking-widest text-gray-800 transition-all hover:border-green-700 hover:text-green-700 font-bold"
            >
              Back to Home
            </button>
          </div>
        </div>
        <div className="lg:block hidden">
          <Image src={paymentSuccess} alt="payment success" />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(success);
